Added exit codes

diff --git a/gitsp b/gitsp
--- a/gitsp
+++ b/gitsp
@@ -4,6 +4,7 @@
 if [ $# -eq 0 ] 
 then
 	echo 'Error: No gitsp command given' >&2
+	exit 1
 fi
 
 # gitsp init <remote_url>
@@ -16,6 +17,7 @@ then
 		git remote add origin $2
 	else 
 		echo 'Error: Invalid args for INIT, run with "gitsp init <remote_url>"' >&2
+		exit 1
 	fi 
 
 # gitsp send <files> <commit_msg> [<branch>]
@@ -34,6 +36,7 @@ then
                 git push origin $4 
 	else 
 		echo 'Error: Invalid args for SEND, run with "gitsp send <files> <commit_msg> [<branch>]"' >&2
+		exit 1
 	fi
 
 # gitsp pull [<branch>]
@@ -50,11 +53,11 @@ then
 		git pull origin master
 	else
 		echo 'Error: Invalid args for PULL, run with "gitsp pull [<branch>]"' >&2
+		exit 1
 	fi
 
 	git stash apply
 		
-
 # gitsp create <branch>
 # create a new local branch
 elif [ $1 == 'create' ]
@@ -64,7 +67,8 @@ then
 		git checkout -b $2
 	else 
 		echo 'Error: Invalid args for CREATE, run with "gitsp create <branch>"' >&2
-        fi
+        	exit 1
+	fi
 
 # gitsp switch <branch>
 # switch to an existing local branch
@@ -75,7 +79,8 @@ then
 		git checkout $2
 	else 
 		echo 'Error: Invalid args for SWITCH, run with "gitsp switch <branch>"' >&2
-        fi 
+        	exit 1
+	fi 
 
 # gitsp user <username> <email>
 # configure user credentials for commits
@@ -87,33 +92,46 @@ then
 		git config --global user.email "$3"
 	else
 		echo 'Error: Invalid args for USER, run with "gitsp user <username> <email>"' >&2
-        fi 
+        	exit 1
+	fi 
 
 # gitsp info
 # show info related to current local repository
-elif [ $1 == 'info' ] && [ $# == 1 ] 
+elif [ $1 == 'info' ] 
 then
-	echo
-	echo "Username: "$(git config user.name)
-	echo "Email: "$(git config user.email)
-	echo "Remote URL: "$(git config remote.origin.url)
-	echo "Branches:"
-	git branch
-	echo
+	if [ $# == 1 ] 
+	then
+		echo
+		echo "Username: "$(git config user.name)
+		echo "Email: "$(git config user.email)
+		echo "Remote URL: "$(git config remote.origin.url)
+		echo "Branches:"
+		git branch
+		echo
+	else 
+		echo 'Error: Invalid args for INFO, run with "gitsp info"' >&2
+		exit 1
+	fi
 
 # gitsp help
 # show all available commands
-elif [ $1 == 'help' ] && [ $# == 1 ]
+elif [ $1 == 'help' ]
 then
-	echo
-	echo 'Available gitsp commands:'
-	echo 'gitsp init <remote_url>'
-	echo 'gitsp send <files> <commit_msg> [<branch>]'
-	echo 'gitsp pull [<branch>]'
-	echo 'gitsp create <branch>'
-	echo 'gitsp switch <branch>'
-	echo 'gitsp user <username> <email>'
-	echo 'gitsp info'
-	echo
-
+	if [ $# == 1 ]
+	then
+		echo
+		echo 'Available gitsp commands:'
+		echo 'gitsp init <remote_url>'
+		echo 'gitsp send <files> <commit_msg> [<branch>]'
+		echo 'gitsp pull [<branch>]'
+		echo 'gitsp create <branch>'
+		echo 'gitsp switch <branch>'
+		echo 'gitsp user <username> <email>'
+		echo 'gitsp info'
+		echo
+	else 
+		echo 'Error: Invalid args for HELP, run with "gitsp help"' >&2
+		exit 1
+	fi
 fi
+
